// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejU9euNTGJ0EqtuJ2hJGBhgNi2qw05W4',
    appId: '1:980721620844:web:cd02b21c40935f6f340549',
    messagingSenderId: '980721620844',
    projectId: 'destinymatch-70b72',
    authDomain: 'destinymatch-70b72.firebaseapp.com',
    databaseURL: 'https://destinymatch-70b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinymatch-70b72.appspot.com',
    measurementId: 'G-CNRJQBN4MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_0pw3WWyKwMWEvGQPetpzIsWYHBtiHQ',
    appId: '1:980721620844:android:ae8040e114f4e3aa340549',
    messagingSenderId: '980721620844',
    projectId: 'destinymatch-70b72',
    databaseURL: 'https://destinymatch-70b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinymatch-70b72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsG56vEYE7eqi_N--QC-C_XO--kmwRA8I',
    appId: '1:980721620844:ios:8ed6451927f0bceb340549',
    messagingSenderId: '980721620844',
    projectId: 'destinymatch-70b72',
    databaseURL: 'https://destinymatch-70b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinymatch-70b72.appspot.com',
    iosBundleId: 'com.example.flutterChatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsG56vEYE7eqi_N--QC-C_XO--kmwRA8I',
    appId: '1:980721620844:ios:8ed6451927f0bceb340549',
    messagingSenderId: '980721620844',
    projectId: 'destinymatch-70b72',
    databaseURL: 'https://destinymatch-70b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinymatch-70b72.appspot.com',
    iosBundleId: 'com.example.flutterChatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejU9euNTGJ0EqtuJ2hJGBhgNi2qw05W4',
    appId: '1:980721620844:web:af86fc4530b103e5340549',
    messagingSenderId: '980721620844',
    projectId: 'destinymatch-70b72',
    authDomain: 'destinymatch-70b72.firebaseapp.com',
    databaseURL: 'https://destinymatch-70b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinymatch-70b72.appspot.com',
    measurementId: 'G-DRVCTGFT7Z',
  );
}
